# Generated by Django 3.2.16 on 2023-01-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('address1', models.TextField(max_length=100)),
                ('address2', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
