# Generated by Django 3.2.16 on 2023-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='address1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='address2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='phonenumber',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
