# Generated by Django 3.2.16 on 2023-01-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230120_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('total_price', models.CharField(blank=True, default=0, max_length=20)),
                ('order_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(default=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(default=True, max_length=200, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='shop.registermodel')),
                ('order_items', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='shop.cartmodel')),
            ],
        ),
    ]
