# Generated by Django 3.2.16 on 2023-01-23 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='testorders',
            fields=[
                ('total_price', models.CharField(blank=True, default=0, max_length=20)),
                ('order_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(default=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(default=True, max_length=200, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('authorised', 'Authorised'), ('Captured', 'Capured')], max_length=100)),
                ('customer', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='shop.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=10)),
                ('prod_image', models.ImageField(upload_to='uploads\\products')),
                ('order', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='shop.testorders')),
            ],
        ),
    ]
