# Generated by Django 3.2.16 on 2023-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230123_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='total_price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
